# https://docs.spring.io/spring-boot/docs/2.2.x/reference/html/common-application-properties.html

debug: false
trace: false

logging.level:
  org.springframework.boot.autoconfigure: ERROR

server:
  port: 5000

jwt:
  secret: javainuse

spring:
  application.name: Blockchain Contest
  profiles:
    active: local
  main.allow-bean-definition-overriding: false
  output:
    ansi:
      enabled: always  # https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/boot-features-logging.html#boot-features-logging-color-coded-output
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-enabling-endpoints
management.endpoints:
  enabled-by-default: true
  shutdown.enabled: true
  web.exposure.include: "*"

ethereum:
  gasLimit: 10_000_000    # '_' as a thousand separtor only for Java 7 or higher
  gasPrice: 0   # 0 for Besu, Ganache, or Ganache CLI 
  client:
    protocol: 'https'   # 'http' or 'https'
    host: 'besu.chainz.network'   # '127.0.0.1' for local client or 'besutest.chainz.network' for ChainZ test network
    port: 443
    jwt: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJuZXQ6KiIsImV0aDoqIiwiZGVidWc6KiIsInR4cG9vbDoqIiwiZWVhOioiXSwiZXhwIjoxNjA3MTQ2MDE3LCJ0ZWFtIjoiMDEifQ.vXDDJN8tUBpcX1e593fZB__XkHwXl-F6IcbJUf1HUA-yvwiJLvBfy_t0FtI0rjqUCX4T2_TTYxqTMsAo_dQAcQGW8ClT1y6UaW4ZghvS5vJw4tnQumqoVDn8JznrkMsBjyB6ZzGPR9hpB8UdcTIo9NJ2z7exRZPdWnzgroAObLmCAIH9OLdUu570FQ9hFDXpEAHPsZiHI72W67CP6LYm0pl7ztWP3F7PKYETlz3seHnir9_cwIOjR_m121C0IDeubxuoLPbz6bDP2gQzhTU3FmRa769_NlhRyc1Tptd7fO_lpM6QQJr8VNcDB5Ouo5IdGzkRBryaOtFFPJ33nrrT-Q'
  
sampleContracts:
    simpleCoin.address: '0xABa7902442c5739c6f0c182691d48D63d06A212E'

smartContracts:
    batteryCertificates.address: '0xffB55C1f49E29FE8f09cb8f43f57Ebaa225380fd'

credentials:
  default:
    password: '1234'
    path: 'src/main/resources/credentials/ca1fe1c6382be7563f7a57a53932a23f702a43a5.json'
  buyer:
    password: '1234'
    path: 'src/main/resources/credentials/2bc06b1a8a1cbddf3c63ae3e78f9ffc9d38c303c.json'
  seller:
    password: '1234'
    path: 'src/main/resources/credentials/36c7744371a858542c5cf51adc040492bfa48487.json'

resttemplate:
  base:
    url: http://localhost:8080
---
spring:
  profiles: dev
   
---
spring:
  profiles: prod
  
  
   